[tool.poetry]
name = "satellites"
version = "0.1.0"
description = ""
authors = ["Johanna Lehto <johannaeveliinalehto@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.4"
uvicorn = "^0.32.0"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
skyfield = "^1.49"
pre-commit = "^4.0.1"
pymongo = {extras = ["srv"], version = "^4.10.1"}
pydantic = "^2.9.2"
astropy = "^6.1.5"
celery = "^5.4.0"
redis = "^5.2.1"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.3.1"
pytest = "^8.3.3"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
